export const components = [
  {
    id: 1,
    title: "Detalles interactivos de la tarjeta",
    description:
      "Componente para ingresar información de tarjetas de crédito y mostrar su actualización en tiempo real.",
    tools: ["JavaScript", "CSS"],
    category: "component",
    web: "https://stalinam.github.io/expenses-chart-component/",
    repository: "https://github.com/StalinAM/expenses-chart-component",
  },
  {
    id: 2,
    title: "Gráfico de gastos",
    description:
      "Componente que muestra un gráfico de los gastos de la semana anterior.",
    tools: ["JavaScript", "CSS"],
    category: "component",
    web: "https://stalinam.github.io/InteractiveCardDetailsForm/",
    repository: "https://github.com/StalinAM/InteractiveCardDetailsForm",
  },
  {
    id: 3,
    title: "Tarjeta NFT",
    description: "Componente de carta para mostrar información de un NFT.",
    tools: ["HTML", "CSS"],
    category: "component",
    web: "https://stalinam.github.io/NFT-PreviewCard/",
    repository: "https://github.com/StalinAM/NFT-PreviewCard",
  },
  {
    id: 4,
    title: "Agenda telefónica",
    description: "API para administrar números de contacto.",
    tools: ["Express", "Mongoose"],
    category: "component",
    web: "https://kind-red-turtle-tie.cyclic.app/api/persons",
    repository: "https://github.com/StalinAM/starter-express-api",
  },
];
export const data = [
  {
    id: 17,
    image: "https://i.ibb.co/n7hTb33/1.webp",
    title: "Daniks Shop",
    description:
      "Aplicación de tienda en línea que permite a los usuarios realizar compras y los redirige a WhatsApp con los detalles de los productos seleccionados.",
    tools: ["React.js", "Firebase", "React Router", "Styled-components"],
    category: "complete",
    web: "https://www.linkedin.com/posts/stalinam_hola-comunidad-de-linkedin-hoy-estoy-emocionado-activity-7086883471536627713-6sPP?utm_source=share&utm_medium=member_desktop",
    repository: "https://github.com/StalinAM/product_catalog",
  },
  {
    id: 16,
    image: "https://i.ibb.co/DrtNXcK/aluraflix.webp",
    title: "Aluraflix",
    description:
      "Plataforma similar a Netflix, pero enfocada en los cursos de Alura. Aquí los usuarios podrán explorar una amplia gama de cursos organizados por categorías, y tendrán la capacidad de contribuir al contenido al agregar nuevos videos y categorías.",
    tools: [
      "React.js",
      "Tailwind",
      "React Router",
      "Json-Server",
      "React-slick",
    ],
    category: "complete",
    web: "https://svam-aluraflix.netlify.app/",
    repository: "https://github.com/StalinAM/aluraflix",
  },
  {
    id: 15,
    image: "https://i.ibb.co/wJ09TwQ/2.webp",
    title: "EasyMoney",
    description:
      "App web de finanzas personales, diseñada para simplificar la gestión del dinero, permite llevar un seguimiento rápido y fácil de los gastos y te ayuda a ahorrar.",
    tools: ["React.js", "Firebase", "React Router", "Styled-components"],
    category: "complete",
    web: "https://easy-money-app.vercel.app/",
    repository: "https://github.com/StalinAM/easy-money-app.git",
  },
  {
    id: 14,
    image: "https://i.ibb.co/0q7YLMP/4.webp",
    title: "Hydra",
    description:
      "Desarrollé este sitio web siguiendo un diseño proporcionado por Zine, incluyendo efectos que crean una experiencia de realidad virtual.",
    tools: ["React.js", "Styled-components", "Atropos"],
    category: "complete",
    web: "https://hydravr.netlify.app/",
    repository: "https://github.com/StalinAM/hydra-landing-page.git",
  },
  {
    id: 13,
    image: "https://i.ibb.co/h27MMfk/project9.webp",
    title: "GalloExpre C.A.",
    description:
      "Llevé a cabo el desarrollo de este proyecto con el objetivo de optimizar el rendimiento de la página original. Además, se optó por un diseño minimalista y funcional para modernizar la apariencia de la página.",
    tools: ["React.js", "Styled-components"],
    category: "complete",
    web: "https://stalinam.github.io/galloexpre/",
    repository: "https://github.com/StalinAM/galloexpre.git",
  },
  {
    id: 12,
    image: "https://i.ibb.co/qmxdf6d/project8.webp",
    imageBig: "https://i.ibb.co/t2qR2gp/3.webp",
    title: "Space Turism",
    description:
      "El sitio web de turismo espacial brinda información detallada sobre los destinos, la tripulación y la tecnología avanzada empleada en cada viaje interestelar.",
    tools: ["React.js", "Next.js", "React Dom"],
    category: "complete",
    web: "https://space-tourism-svam.vercel.app/",
    repository: "https://github.com/StalinAM/space-tourism.git",
  },
  {
    id: 11,
    image: "https://i.ibb.co/jM0hsCc/project7.webp",
    title: "Piedra, Papel o Tijera",
    description:
      "Sitio web para jugar a Piedra, Papel o Tijera con una interfaz sencilla y fácil de usar.",
    tools: ["React.js", "Styled Components", "React Router"],
    category: "complete",
    web: "https://stalinam.github.io/rock-paper-scissers-react/",
    repository: "https://github.com/StalinAM/rock-paper-scissers-react",
  },
  {
    id: 10,
    image: "https://i.ibb.co/k6TJNPR/project6.webp",
    title: "Portafolio",
    description:
      "Mi portafolio web donde encontrarás mi trabajo y habilidades en diseño, desarrollo y tecnología, con ejemplos de proyectos anteriores.",
    tools: ["React.js", "Styled Components", "React Router"],
    category: "complete",
    web: "https://svam-v1.netlify.app/",
    repository: "https://github.com/StalinAM/portfolio-figma",
  },
  {
    id: 9,
    image: "https://i.ibb.co/tsppYSn/project5.webp",
    title: "Plantilla para portafolio web",
    description:
      "Portafolio de desarrollador web que cuenta con varias secciones, donde se exhiben los proyectos filtrados por categorías y con un formulario de contacto.",
    tools: ["React.js", "Styled Components"],
    category: "complete",
    web: "https://template-portfolio-svam.netlify.app/",
    repository: "https://github.com/StalinAM/PortfolioPersonal",
  },
  {
    id: 8,
    image: "https://i.ibb.co/wMzG9VX/project4.webp",
    title: "Sunnyside",
    description:
      "Página web de una agencia creativa en la que se exhiben los servicios, testimonios y diseños de la agencia.",
    tools: ["JavaScript", "CSS"],
    category: "complete",
    web: "https://stalinam.github.io/sunny-agengy/",
    repository: "https://github.com/StalinAM/sunny-agengy",
  },
  {
    id: 7,
    image: "https://i.ibb.co/C9SJP3s/project3.webp",
    title: "Crowdfunding",
    description:
      "Página para recaudar fondos mediante campañas. Con ella, se puede visualizar el progreso de la meta y la participación de los apoyadores en tiempo real.",
    tools: ["JavaScript", "CSS"],
    category: "complete",
    web: "https://stalinam.github.io/crowfunding-product-page/",
    repository: "https://github.com/StalinAM/crowfunding-product-page",
  },
  {
    id: 6,
    image: "https://i.ibb.co/0K1FCvr/project2.webp",
    title: "Aplicación Generadora de Consejos",
    description:
      "Sitio web en el cual al hacer clic en el icono verde, se genera un consejo aleatorio mediante una llamada a una API.",
    tools: ["React.js", "CSS", "API Advice Slip"],
    category: "complete",
    web: "https://stalinam.github.io/adviceGeneratorApp/",
    repository: "https://github.com/StalinAM/adviceGeneratorApp",
  },
  {
    id: 5,
    image: "https://i.ibb.co/1RyJFZM/project1.webp",
    title: "Fylo",
    description:
      "Página web de servicios en la nube que presenta los servicios y testimonios, con un módulo incorporado para ingresar y validar direcciones de correo electrónico.",
    tools: ["JavaScript", "CSS"],
    category: "complete",
    web: "https://stalinam.github.io/fylo/",
    repository: "https://github.com/StalinAM/fylo",
  },
];
